# version 1.0.0


# mypy
[tool.mypy]
python_version = "3.12"

[[tool.mypy.overrides]]
module = [
    "pandas"
]
ignore_missing_imports = true


# Ruff
[tool.ruff]
exclude = [
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".venv",
    ".vscode",
]
line-length = 79
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN002",   # missing-type-args
    "ANN003",   # missing-type-kwargs
    "COM812",   # missing-trailing-comma
    "D400",     # ends-in-period
    "D415",     # ends-in-punctuation
    "ERA001",   # commented-out-code
    "FIX002",   # line-contains-todo
    "Q000",     # bad-quotes-inline-string
    "T201",     # print
    "TD002",    # missing-todo-author
    "TD003",    # missing-todo-link
]
fixable = ["ALL"]
unfixable = [
    "F401",     # unused-import
]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"
