# version 1.0.0

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
exclude = [
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".venv",
    ".vscode",
]
line-length = 119
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # Annotation
    "ANN002",  # Missing type annotation for `*args`
    "ANN003",  # Missing type annotation for `**kwargs`
    # Comment
    "ERA001",  # Found commented-out code
    "FIX002",  # Line contains TODO, consider resolving the issue
    "TD002",   # Missing author in TODO
    "TD003",   # Missing issue link on the line following this TODO
    # Others
    "T201",    # `print` found
]
fixable = ["ALL"]
unfixable = [
    "F401",    # imported but unused
]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"
